###########################################################################################################
# Script intended for a tutorial test case 02_charged_drag_on_sphere in Pantera PIC-DSMC code.            #
# --------------------------------------------------------------------------------------------------------#
# This script reads the simulation data from a VTK file, processes it to calculate the force              #
# on a sphere due to charged drag, and then plots the results alongside experimental data.                #
#                                                                                                         #
# NOTE: Make sure to run this script with Paraview's Python environment due to the paraview package usage #
###########################################################################################################

# Import necessary libraries
import numpy as np
import scipy.constants as sc
import matplotlib.pyplot as plt
from scipy.special import erf
from paraview.simple import *


# Set up species parameters for the simulation
# We use mercury gas and assume boundary conditions in default input file for Pantera
particle_mass        = sc.m_u*200
particle_density     = 1e14
particle_velocity    = 10000
particle_temperature = 3000

sphere_radius      = 9.5e-3
sphere_temperature = 300
sphere_potential   = -100

# Path for VTK files generated by Pantera simulation with time step 2000, adjust if necessary
folder_path = 'dumps'
timestep = 3000


##################################################
##################################################
##################################################

# ----------------------------
# ----- SOURCE FUNCTIONS -----
# ----------------------------

def get_Cd(S,T,Tw):
    return np.exp(-S**2)/(np.sqrt(np.pi)*S**3)*(2*S**2+1) + erf(S)*(4*S**4+4*S**2-1)/(2*S**4) + 2*np.sqrt(np.pi)*np.sqrt(Tw/T)/3/S

def get_force(folder,timestep,parameters):


    m, n, u, T, R, Tw, phi = parameters
    rho = m*n
    A = R**2*np.pi
    S = u/np.sqrt(2*sc.k*T/m)
    C_d = get_Cd(S,T,Tw)
    E = 0.5*m*u**2

    F_N = 0.5*rho*u**2*A*C_d

    alpha_arr = np.array([])
    force_arr = np.array([])

    # Load your dataset (replace 'YourFile.vtk' with your file)
    data = OpenDataFile(folder+'/dsmc_boundary_'+str(timestep)+'.vtk')

    # Threshold to filter the specific PHYS_GROUP (adjusted for cell data)
    phys_group_id = 4  # Replace with the desired PHYS_GROUP ID
    threshold = Threshold(Input=data)
    threshold.Scalars = ['CELLS', 'PHYSICAL_GROUP']  # Use CELLS instead of POINTS
    threshold.LowerThreshold = phys_group_id
    threshold.UpperThreshold = phys_group_id

    # Generate the geometry to get line segments explicitly
    geometry = ExtractSurface(Input=threshold)

    # Fetch the processed geometry for further calculations
    geometry.UpdatePipeline()
    data_info = servermanager.Fetch(geometry)

    # Sum variable contributions
    pem_sum = 0.0
    mom_sum = 0.0

    # Iterate over each line segment (cell)
    for j in range(data_info.GetNumberOfCells()):
        # Get cell length (assuming 2D line segments)
        cell = data_info.GetCell(j)
        p0 = cell.GetPoints().GetPoint(0)
        p1 = cell.GetPoints().GetPoint(1)
        length = ((p1[0] - p0[0])**2 + (p1[1] - p0[1])**2)**0.5  # Euclidean distance

        # Get the variable value for the cell (e.g., flux)
        pem_x = data_info.GetCellData().GetArray('pem_x').GetValue(j)
        mom_x = data_info.GetCellData().GetArray('mom_x_in_Hg+').GetValue(j)
        mom_x+= data_info.GetCellData().GetArray('mom_x_out_Hg+').GetValue(j)
        
        # Add contribution to total sum
        mom_sum += mom_x*length*(p0[1] + p1[1])/2*2*np.pi
        pem_sum += pem_x*length*(p0[1] + p1[1])/2*2*np.pi

    
    F_direct = mom_sum
    F_indirect = pem_sum

    alpha_arr = np.append(alpha_arr,sc.e*np.abs(phi)/E)
    force_arr = np.append(force_arr,(F_direct+F_indirect)/F_N)

    return alpha_arr, force_arr


def plot(folder,timestep,parameters):

    fig,axs = plt.subplots(1,1,figsize=(8,6))

    exp_data_r1 = np.loadtxt('reference_data/expdata_r9mm.csv',delimiter=',').T
    exp_data_r2 = np.loadtxt('reference_data/expdata_r12mm.csv',delimiter=',').T

    axs.plot(exp_data_r1[0],exp_data_r1[1],"^",
            label=r'Experiment (Knechtel et al, 1964) - $r_1 = 9.5 \: \mathrm{mm}$',
            color='darkred',
            markerfacecolor='none',
            ms=6)
    axs.plot(exp_data_r2[0],exp_data_r2[1],"^",
            label=r'Experiment (Knechtel et al, 1964) - $r_2 = 12.5 \: \mathrm{mm}$',
            color='darkblue',
            markerfacecolor='none',
            ms=6)

    capon_r9_n1 = np.loadtxt('reference_data/capon_r9_n1.csv',delimiter=',').T
    axs.plot(capon_r9_n1[0],capon_r9_n1[1],"s-",
            label=r'Numerical (Capon et al, 2019) - $r_1, n = 10^{14} \ \mathrm{m^{-3}}$',
            color='darkblue',
            ms=6)



    alpha_n1r1, force_n1r1 = get_force(folder,timestep,parameters)
    axs.plot(alpha_n1r1,force_n1r1,"o",
            label=r'Pantera simulation',
            color='red',
            mfc='none',
            ms=10,
            mew=3)


    axs.legend()
    fig.tight_layout()
    plt.show()


# Call the plotting function
plot(folder=folder_path, timestep=timestep,
     parameters = [particle_mass,
            particle_density,
            particle_velocity,
            particle_temperature,
            sphere_radius,
            sphere_temperature,
            sphere_potential])